# ***Project 4 : Dataframe***

**nous allons utiliser deux sources de données :**

* **Les émissions de gaz à effet de serre estimées au niveau communal par l’ADEME. Le jeu de données est disponible sur data.gouv et requêtable directement dans Python avec cet url.**
* **Idéalement, on utiliserait directement les données disponibles sur le site de l’Insee mais celles-ci nécessitent un peu de travail de nettoyage qui n’entre pas dans le cadre de ce TP. Pour faciliter l’import de données Insee, il est recommandé d’utiliser le package pynsee qui simplifie l’accès aux données de l’Insee disponibles sur le site web insee.fr ou via des API.**

### **Importer un CSV et explorer la structure de données**

**L’URL d’accès aux données :**

**url = "https://koumoul.com/s/data-fair/api/v1/datasets/igt-pouvoir-de-rechauffement-global/convert"**

1 **Importer les données de l’Ademe à l’aide du package Pandas et de la commande consacrée pour l’import de csv. Nommer le DataFrame obtenu emissions1.**

In [72]:
import pandas as pd

In [73]:
emissions1 = pd.read_csv("IGT - Pouvoir de réchauffement global.csv")

In [74]:
emissions1

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,NaN,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934
3,01005,AMBERIEUX-EN-DOMBES,1859.160954,NaN,NaN,1144.429311,216.217508,94.182310,276.448534,663.683146,1756.341319,782.404357
4,01006,AMBLEON,448.966808,NaN,NaN,77.033834,48.401549,NaN,NaN,43.714019,398.786800,51.681756
...,...,...,...,...,...,...,...,...,...,...,...,...
35793,95676,VILLERS-EN-ARTHIES,1628.065094,NaN,NaN,165.045396,65.063617,11.772789,34.556067,176.098160,309.627908,235.439109
35794,95678,VILLIERS-ADAM,698.630772,NaN,NaN,1331.126598,111.480954,2.354558,6.911213,1395.529811,18759.370071,403.404815
35795,95680,VILLIERS-LE-BEL,107.564967,NaN,NaN,8367.174532,225.622903,534.484607,1568.845431,22613.830247,12217.122402,13849.512001
35796,95682,VILLIERS-LE-SEC,1090.890170,NaN,NaN,326.748418,108.969749,2.354558,6.911213,67.235487,4663.232127,85.657725
35797,95690,WY-DIT-JOLI-VILLAGE,1495.103542,NaN,NaN,125.236417,97.728612,4.709115,13.822427,117.450851,504.400972,147.867245

2. **Utiliser les méthodes adéquates afin d’afficher pour les 10 premières valeurs, les 15 dernières et un échantillon aléatoire de 10 valeurs grâce aux méthodes adéquates du package Pandas.**

In [75]:
# Les 10 premières valeurs
emissions1.head(10)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,NaN,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934
3,01005,AMBERIEUX-EN-DOMBES,1859.160954,NaN,NaN,1144.429311,216.217508,94.182310,276.448534,663.683146,1756.341319,782.404357
4,01006,AMBLEON,448.966808,NaN,NaN,77.033834,48.401549,NaN,NaN,43.714019,398.786800,51.681756
5,01007,AMBRONAY,4390.996698,132.968268,NaN,3067.245459,6144.186081,122.437003,359.383094,1898.638273,22481.123575,2789.133106
6,01008,AMBUTRIX,489.648726,60.233517,NaN,558.055709,98.388885,2.354558,6.911213,495.393592,3616.168396,356.029873
7,01009,ANDERT-ET-CONDON,676.468367,NaN,NaN,207.181968,149.767083,2.354558,6.911213,141.533662,696.956038,161.266219
8,01010,ANGLEFORT,1070.411510,143.815664,NaN,1286.621447,146.525382,341.410872,175185.892467,448.518801,3199.808360,1206.147643
9,01011,APREMONT,2010.790441,NaN,NaN,249.086914,52.103791,2.354558,6.911213,151.844891,686.153720,188.542701

In [76]:
# Les 15 dernières valeurs
emissions1.tail(15)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
35783,95628,VALMONDOIS,646.421867,9.055189,0.201508,633.754921,158.691749,136.564349,400.850374,2272.901317,589.164544,574.241730
35784,95633,VAUDHERLAND,48.361025,NaN,NaN,47.061403,10.314964,2.354558,6.911213,34.490233,439.279632,199.435133
35785,95637,VAUREAL,203.969473,93.811651,5.412508,2876.820106,129.738126,63.573059,186.602760,13963.143585,4982.982966,7515.388640
35786,95641,VEMARS,1510.886844,146.089307,NaN,2382.550523,19.173651,251.937678,739.499829,2791.215196,17783.179831,2654.384495
35787,95651,VETHEUIL,125.928390,175.096168,10.102258,290.066886,114.522546,16.481904,48.378493,1439.077120,1472.779256,414.411115
35788,95652,VIARMES,252.094735,55.168176,NaN,1278.247866,43.526914,40.027482,117.490627,6546.179324,5705.777606,2521.399729
35789,95656,VIENNE-EN-ARTHIES,324.827105,NaN,NaN,98.346155,57.129030,2.354558,6.911213,158.726900,305.819555,206.727023
35790,95658,VIGNY,1289.190261,NaN,NaN,1616.838995,2297.572718,313.156180,919.191376,1424.373138,8539.961119,516.817557
35791,95660,VILLAINES-SOUS-BOIS,447.132894,18.996282,NaN,207.294216,92.966916,11.772789,34.556067,1023.037832,912.992023,336.409947
35792,95675,VILLERON,1335.123315,4.975886,NaN,1625.523404,104.075339,320.219853,939.925016,617.177184,7740.572805,725.467969
35793,95676,VILLERS-EN-ARTHIES,1628.065094,NaN,NaN,165.045396,65.063617,11.772789,34.556067,176.098160,309.627908,235.439109
35794,95678,VILLIERS-ADAM,698.630772,NaN,NaN,1331.126598,111.480954,2.354558,6.911213,1395.529811,18759.370071,403.404815
35795,95680,VILLIERS-LE-BEL,107.564967,NaN,NaN,8367.174532,225.622903,534.484607,1568.845431,22613.830247,12217.122402,13849.512001
35796,95682,VILLIERS-LE-SEC,1090.890170,NaN,NaN,326.748418,108.969749,2.354558,6.911213,67.235487,4663.232127,85.657725
35797,95690,WY-DIT-JOLI-VILLAGE,1495.103542,NaN,NaN,125.236417,97.728612,4.709115,13.822427,117.450851,504.400972,147.867245

In [77]:
# Echantillon aléatoire de 10 valeurs
emissions1.sample(10)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
23645,60513,PRECY-SUR-OISE,725.043383,471.675106,24.003927,2629.156671,26.492847,113.018772,331.738241,4683.918352,5135.581759,1596.368503
8332,24231,LAVALADE,535.758784,NaN,NaN,83.936509,13.356556,4.709115,13.822427,57.594502,150.288812,48.332012
35069,89349,SAINT-LEGER-VAUBAN,4997.630123,NaN,NaN,343.185232,51.178089,2.354558,6.911213,203.614549,484.555576,185.192958
3484,10302,PRASLIN,1854.466337,NaN,NaN,159.403990,11.901881,2.354558,6.911213,42.037740,437.217464,43.068130
17361,46156,LAROQUE-DES-ARCS,56.727751,NaN,NaN,423.148684,68.898668,2.354558,6.911213,360.569583,1902.522452,249.316618
33113,82114,MONBEQUI,561.736780,NaN,NaN,462.422329,80.271577,2.354558,6.911213,254.483595,1780.058310,290.470608
7772,22296,SAINT-GLEN,4020.748276,NaN,NaN,379.916856,80.271577,2.354558,6.911213,301.989521,588.352726,290.470608
6650,19144,MONTGIBAUD,4176.717394,NaN,NaN,388.137645,31.077134,16.481904,48.378493,133.163915,509.418130,112.455672
31,01035,BELLEYDOUX,819.908142,NaN,NaN,206.810369,43.243502,2.354558,6.911213,128.335596,665.767586,156.480871
2731,08369,LA ROMAGNE,959.246551,NaN,NaN,158.509185,17.456092,2.354558,6.911213,72.925116,254.806229,63.166590

3. **Tirer 5 pourcents de l’échantillon sans remise.**

In [78]:
pourcentage = 5
taille_echantillon = int((len(emissions1)*pourcentage/100))
echantillon_sans_remise = emissions1.sample(n= taille_echantillon, replace = False)

In [79]:
echantillon_sans_remise

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
1152,02769,VAUX-ANDIGNY,4543.723924,NaN,NaN,2429.107462,127.217886,572.157531,1679.424844,1178.776335,1734.211913,460.350453
22751,59266,GONDECOURT,880.116746,NaN,NaN,7200.565721,32.366379,1958.992041,5750.129508,6084.738317,3152.493698,2683.002488
12450,32250,MEILHAN,1089.475296,NaN,NaN,91.922458,11.505152,2.354558,6.911213,43.876391,297.686662,41.632525
11860,31247,LABARTHE-RIVIERE,2189.202322,57.018489,NaN,1236.915627,179.189434,70.636732,207.336401,1735.228406,3612.508893,648.414620
2346,07293,SAINT-ROMAIN-DE-LERPS,1545.339079,NaN,NaN,398.668502,140.575007,2.354558,6.911213,369.674980,245.070357,385.220494
...,...,...,...,...,...,...,...,...,...,...,...,...
1357,03144,LIERNOLLES,19146.312291,NaN,NaN,418.767414,27.903299,2.354558,6.911213,121.151771,954.215292,100.970837
18750,50587,TAILLEPIED,4397.850831,NaN,NaN,36.411108,3.438321,2.354558,6.911213,14.436576,105.677134,12.441904
17410,46206,MONTLAUZUN,910.297912,NaN,NaN,108.836238,16.927120,2.354558,6.911213,66.278823,291.462153,61.252451
20515,54417,PAREY-SAINT-CESAIRE,1684.557654,NaN,NaN,169.437349,30.151432,2.354558,6.911213,117.991884,321.720881,109.105929
23482,60345,LAMECOURT,600.061371,NaN,NaN,154.605863,28.696758,2.354558,6.911213,83.499176,66.021198,103.842046

4. **Ne conserver que les 10 premières lignes et tirer aléatoirement dans celles-ci pour obtenir un DataFrame de 100 données.**

In [80]:
les_dix_premieres_lignes = emissions1.head(10)
alt = les_dix_premieres_lignes.sample(n = 100 , replace = True)
alt

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
6,01008,AMBUTRIX,489.648726,60.233517,NaN,558.055709,98.388885,2.354558,6.911213,495.393592,3616.168396,356.029873
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207
...,...,...,...,...,...,...,...,...,...,...,...,...
5,01007,AMBRONAY,4390.996698,132.968268,NaN,3067.245459,6144.186081,122.437003,359.383094,1898.638273,22481.123575,2789.133106
6,01008,AMBUTRIX,489.648726,60.233517,NaN,558.055709,98.388885,2.354558,6.911213,495.393592,3616.168396,356.029873
8,01010,ANGLEFORT,1070.411510,143.815664,NaN,1286.621447,146.525382,341.410872,175185.892467,448.518801,3199.808360,1206.147643
7,01009,ANDERT-ET-CONDON,676.468367,NaN,NaN,207.181968,149.767083,2.354558,6.911213,141.533662,696.956038,161.266219
7,01009,ANDERT-ET-CONDON,676.468367,NaN,NaN,207.181968,149.767083,2.354558,6.911213,141.533662,696.956038,161.266219

5. **Faire 100 tirages à partir des 6 premières lignes avec une probabilité de 1/2 pour la première observation et une probabilité uniforme pour les autres.**

In [81]:
import numpy as np
Les_six_premières_lignes = emissions1.head(6)

In [82]:
proba = [0.5] + [0.5/5]*5

In [83]:
tir = np.random.choice(Les_six_premières_lignes.index,size = 100,p = proba)
df2 = emissions1.loc[tir]

In [84]:
df2

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,NaN,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
3,01005,AMBERIEUX-EN-DOMBES,1859.160954,NaN,NaN,1144.429311,216.217508,94.182310,276.448534,663.683146,1756.341319,782.404357
...,...,...,...,...,...,...,...,...,...,...,...,...
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,NaN,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
3,01005,AMBERIEUX-EN-DOMBES,1859.160954,NaN,NaN,1144.429311,216.217508,94.182310,276.448534,663.683146,1756.341319,782.404357